### ISSUE TITLE
Ubuntu GKE error="specific kernel headers not found"

### ISSUE THREAD

**Issue by nicolassdiaz** [falcosecurity/driverkit#67]
**Describe the bug**

I am trying to build for a ubuntu gke but I get the error: 

error="specific kernel headers not found"

**How to reproduce it**

./driverkit docker --output-module falco_ubuntu-generic_4.15.0-1044-gke_46.ko --kernelversion=46 --kernelrelease=4.15.0-1044-gke --driverversion=dev --target=ubuntu-generic

**Expected behaviour**

Successful build using the kernel options

**Environment**
4.15.0-65-generic

- System info:

- Cloud provider or hardware configuration:
- OS:
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
- Kernel:
Linux k3s 4.15.0-65-generic #74-Ubuntu
- Installation method:
docker

**Comment by leogr** [comment]
AFAIK there's no GKE builder implemented yet (see https://github.com/falcosecurity/driverkit/issues/60 ), so `driverkit` cannot build the driver with `--kernelversion=46 --kernelrelease=4.15.0-1044-gke`.

Note: I'm assuming the "Environment" section does not relate to the targeted env, but just one you used to run the command, correct?

**Comment by nicolassdiaz** [comment]
Hi @leogr,

I am trying to install Falco on GKE with Ubuntu and that kernel release, there is another way to build ?.

What do you recommend ? 


note: about env used to build, you are right.

Thank you!

**Comment by fntlnz** [comment]
I think it's because of the `-gke` suffix. I don't see them mirrored here https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux/

We need to add

https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-gke-5.4/
and 
https://mirrors.edge.kernel.org/ubuntu/pool/main/l/linux-gke-4.15/

to the generic pool here https://github.com/falcosecurity/driverkit/blob/feat/debian-cloud-amd64/pkg/driverbuilder/builder/ubuntu.go#L135-L136 since they are generic AND gke, unlike aws which is not generic.
